// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCNcJwpTF4tqp-PzBBgu5Tu0O5icznDZc',
    appId: '1:117129117717:android:f280b541de6b34109a8e1c',
    messagingSenderId: '117129117717',
    projectId: 'todoapp-817d1',
    storageBucket: 'todoapp-817d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD-hlAplmwFoRypL60i6BKXzYlGUg2iic',
    appId: '1:117129117717:ios:9d8d4824228a1f4f9a8e1c',
    messagingSenderId: '117129117717',
    projectId: 'todoapp-817d1',
    storageBucket: 'todoapp-817d1.firebasestorage.app',
    androidClientId: '117129117717-28sg7cjuccrq6jv043mns5o11dggl7va.apps.googleusercontent.com',
    iosClientId: '117129117717-9cihp5ffk21ngvhqo1sp8de861r105tr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

}